name: dart_payway
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
  dotenv: ^3.0.0

dependencies:
  collection: ^1.15.0
  crypto: ^3.0.0-nullsafety.0
  dio: ^4.0.6
  intl: ^0.17.0
  logger: ^1.2.2
